### ISSUE TITLE
Problem with ctd-decoder

### ISSUE THREAD

**Issue by amar-g72** [containerd/imgcrypt#102]
I have cloned containerd/imgcrypt but it is having difficulty with 'ctd-decoder' when I use the 'make' command

[github.com/containerd/containerd/cio](https://github.com/containerd/containerd/cio)

[github.com/containerd/containerd/content](https://github.com/containerd/containerd/content)

# [github.com/containerd/containerd/content](https://github.com/containerd/containerd/content)

vendor/github.com/containerd/containerd/content/helpers.go:236:27: undefined: io.Discard

[github.com/containerd/containerd/mount](https://github.com/containerd/containerd/mount)

# [github.com/containerd/containerd/cio](https://github.com/containerd/containerd/cio)

vendor/github.com/containerd/containerd/cio/io_unix.go:41:14: undefined: os.MkdirTemp

[github.com/containerd/containerd/remotes/errors](https://github.com/containerd/containerd/remotes/errors)

# [github.com/containerd/containerd/remotes/errors](https://github.com/containerd/containerd/remotes/errors)

vendor/github.com/containerd/containerd/remotes/errors/errors.go:43:10: undefined: io.ReadAll

[github.com/containerd/containerd/services/introspection](https://github.com/containerd/containerd/services/introspection)

# [github.com/containerd/containerd/mount](https://github.com/containerd/containerd/mount)

vendor/github.com/containerd/containerd/mount/temp.go:33:16: undefined: os.MkdirTemp

# [github.com/containerd/containerd/services/introspection](https://github.com/containerd/containerd/services/introspection)

vendor/github.com/containerd/containerd/services/introspection/local.go:117:15: undefined: os.ReadFile

vendor/github.com/containerd/containerd/services/introspection/local.go:141:12: undefined: os.WriteFile

make: *** [Makefile:37: bin/ctd-decoder] Error 2

**Comment by stefanberger** [comment]
I think you will need a more recent version of go to compile it. You should probably use g1.18 or later: https://endoflife.date/go

**Comment by stefanberger** [comment]
Did you get it to compile with a later version of go?
