### ISSUE TITLE
typo in README.md file

### ISSUE THREAD

**Issue by atlanboa** [containerd/imgcrypt#104]
it's not issue. it is just a typo

The imgcrypt library provides API exensions **(typo here)** for containerd to support encrypted container images and implements the ctd-decoder command line tool for use by containerd to decrypt encrypted container images. An extended version of containerd's ctr tool (ctr-enc) with support for encrypting and decrypting container images is also provided.

**Comment by stefanberger** [comment]
Fixed. Thanks.
