### ISSUE TITLE
Error seekReader

### ISSUE THREAD

**Issue by CAOLINAN** [containerd/imgcrypt#111]
When I encrypt an image or decrypt it,I get this error: copy failed:unable to resume to resume to blob-xxxxxxxxx :unable to discard to offset.
I have checkd the code and find the reason maybe offset is not none.So how to sove it.I have uploaded many images and no one can run.Why?

**Comment by stefanberger** [comment]
Without you showing the command lines you use to encrypt and decrypt the image, it is nearly impossible to recreate the issue and try to find a solution.

**Comment by stefanberger** [comment]
I am closing this issue now since no information was provided as to how to recreate the issue.
