### ISSUE TITLE
Does it support other algorithms

### ISSUE THREAD

**Issue by ljccc-rbs** [containerd/imgcrypt#139]
in readme, I see create an RSA key pair . So I would like to ask if it supports other algorithms

**Comment by stefanberger** [comment]
Elliptic curve keys can also be used.

**Comment by stefanberger** [comment]
... also GPG keys can be used. It's uses asymmetric crypto. Does this answer your question?

**Comment by stefanberger** [comment]
With key providers it can also use symmetric encryption/decryption.

**Comment by stefanberger** [comment]
To summarize: Built-in algorithms use asymmetric crypto. With external key providers also symmetric crypto can be used.
