### ISSUE TITLE
Protect docker container during run time 

### ISSUE THREAD

**Issue by xcellenceit** [containerd/imgcrypt#17]
Hi,

Just found this from article published on medium at https://medium.com/@lumjjb/encrypting-container-images-with-containerd-imgcrypt-3c07f8e8e8d4

Thanks for sharing detail on how to use this.

Does this also protect docker container during run-time such that no one can see inside?

**Comment by lumjjb** [comment]
Hi, it does not protect the runtime on its own. However it can be used to do that. An example is the following. 

https://medium.com/@pradipta.banerjee/what-you-define-is-what-you-deploy-e55bebef5123

**Comment by lumjjb** [comment]
Answer resolved and no additional follow-up. closing issue.
