### ISSUE TITLE
minify/compress manifest json

### ISSUE THREAD

**Issue by Gsealy** [containerd/imgcrypt#28]
https://github.com/containerd/imgcrypt/blob/36840ad3a650af64eb6e8a7428256823df05ac67/images/encryption/encryption.go#L320

Was the indentation used before for testing? maybe we can compress it to save a little bit size 🤔

**Comment by lumjjb** [comment]
@stefanberger do you remember if there's a technical reason why we do this? or is it just a preference?

**Comment by stefanberger** [comment]
@lumjjb do not remember...

**Comment by stefanberger** [comment]
Other manifests are also marshaled using this function and that's probably where I got it from: 
- https://github.com/containerd/containerd/blob/master/remotes/docker/schema1/converter.go#L176
- https://github.com/containerd/containerd/blob/master/remotes/docker/schema1/converter.go#L200
- https://github.com/containerd/containerd/blob/master/remotes/docker/converter.go#L69

**Comment by Gsealy** [comment]
closed.
