### ISSUE TITLE
Creating a 1.1 release

### ISSUE THREAD

**Issue by stefanberger** [containerd/imgcrypt#34]
Unless someone sees an issue with it, I'll create a 1.1 release on March 5th 2021.

**Comment by stefanberger** [comment]
@estesp @lumjjb

**Comment by lumjjb** [comment]
Don't see why not. Just curious, are we making the versions follow the `ocicrypt` versioning? or a separate versioning for imgcrypt.

**Comment by stefanberger** [comment]
> Don't see why not. Just curious, are we making the versions follow the `ocicrypt` versioning? or a separate versioning for imgcrypt.

We could make a version 1.1 or 2.0. Either way is fine with me.

**Comment by stefanberger** [comment]
Made 1.1 now.
