### ISSUE TITLE
need an updated release and 

### ISSUE THREAD

**Issue by mikebrow** [containerd/imgcrypt#45]
two part...

Current version reports:
   1.5.0-beta.1+unknown

- there have been changes to the ctr command that need to be synched up...  and we should rebase this repo on the 1.5.0 GA to pick that up..  we are going to do a service refresh and imgcrypt binaries are included now so... we should vendor to pick up the new ctr changes, make a release, and set the new release over in containerd/containerd/script/setup/imgcrypt-version

- longer term.. now that we are building this into the release, need a better way to do this and to get the version tag right :-)

cc @dmcgowan

**Comment by lumjjb** [comment]
>there have been changes to the ctr command that need to be synched up... and we should rebase this repo on the 1.5.0 GA to pick that up.. we are going to do a service refresh and imgcrypt binaries are included now so... we should vendor to pick up the new ctr changes, make a release, and set the new release over in containerd/containerd/script/setup/imgcrypt-version

On this, would using nerdctl be a better approach for this? Then we don't have to rely on any patching of `ctr` commands. Would this make things easier?

>longer term.. now that we are building this into the release, need a better way to do this and to get the version tag right :-)

Yea.... the current imgcrypt versions are based off the `ocicrypt` versions, moving to containerd versioning, should we do 1 for every release? or maintain a separate versioning?

@stefanberger thoughts on this?

**Comment by stefanberger** [comment]
> On this, would using `nerdctl` be a better approach for this? Then we don't have to rely on any patching of `ctr` commands. Would this make things easier? In the meantime, we'll update the ctr.

You mean the ctr we are using here? It's just for testing , no other purpose. If it was more serious the encrypted image support in ctr should be in containerd itself ...

**Comment by mikebrow** [comment]
> > On this, would using `nerdctl` be a better approach for this? Then we don't have to rely on any patching of `ctr` commands. Would this make things easier? In the meantime, we'll update the ctr.
> 
> You mean the ctr we are using here? It's just for testing , no other purpose. If it was more serious the encrypted image support in ctr should be in containerd itself ...

note the contents of the release tag.gz

https://github.com/containerd/containerd/pull/5462

and the commits here: https://github.com/containerd/containerd/commit/92ea98eda583168e8951b02a52c099310e9ea636

A meeting of the minds on this .. might be in order :-)

**Comment by lumjjb** [comment]
>A meeting of the minds on this .. might be in order :-)

Yes, it's been a while, would be nice to catch up :) I'll schedule something

**Comment by stefanberger** [comment]
Who is actually using ctr-enc (a[prt from me and the test cases) and should there be two ctr's , one with the encryption stuff and one without it?

**Comment by lumjjb** [comment]
Well I had 1 person slack me about it, so non-zero.. but i did end up asking them to use buildah instead of build his image... so...

**Comment by stefanberger** [comment]
>     * longer term.. now that we are building this into the release, need a better way to do this and to get the version tag right :-)

If enc-ctr functionality stays in imgcrypt, sync'ing the code is the only option --if that's what you mean with 'a better way to do this'.
I don't mind adopting the containerd versioning scheme though if it became necessary to do an imgcrypt release after 1.5.0 for example, it would have to be 1.5.0.1 to not collide with future release of containerd?

Here's what `ctr-enc` shows now after the merge:

```
USAGE:
   ctr-enc [global options] command [command options] [arguments...]

VERSION:
   v1.1.0-10-gd4bdc3b
```

**Comment by stefanberger** [comment]
@mikebrow Can this request be closed?
