### ISSUE TITLE
Is it possible to encrypt local image?

### ISSUE THREAD

**Issue by lannyyip** [containerd/imgcrypt#66]
I tried to encrypt the local images, but it alway check the image from docker.io.
Is it possible to encrypt local image? As in some network configuration, it is not convenient to visit docker.io.
Thank you.

**Comment by lumjjb** [comment]
Yes - you should be able to do this! If you have a way of importing images locally, you can run the encryption routine on these images like you would any other image. I believe the tools don’t require pull on image operations like encryption unless provided a force flag to. 

`nerdctl` would be a good way to do this - docs [here](https://github.com/containerd/nerdctl/blob/master/docs/ocicrypt.md). Also, it would be possible to use skopeo or buildah to do the same if you are more familiar with those tools.

**Comment by lannyyip** [comment]
Thank  you for your quick response. 
Finally, I found out that it is because I load the image with `docker image load`, not `nerdctl image load`. How stupid am I!
Thank you!

Lanny
