### ISSUE TITLE
encryption.CheckAuthorization not working for multi-arch images

### ISSUE THREAD

**Issue by dimitar-dimitrow** [containerd/imgcrypt#69]
When a multi-arch index descriptor is provided to the imgcrypt's CheckAuthorization func (e.g. via image.Target()), the library iterates over the manifests it refers to with the cryptoOpUnwrapOnly option set to true to perform a check only. That causes the cycle to stop on the first manifest in the collection as the condition [here](https://github.com/containerd/imgcrypt/blob/65d749cef36547473d1c1b0b67ed8a4b9e3d13d4/images/encryption/encryption.go#L384) will always be evaluated to true error-regardless. Additionally, if reading any of the referred [manifest's children returns an errdefs.IsNotFound(err)](https://github.com/containerd/imgcrypt/blob/65d749cef36547473d1c1b0b67ed8a4b9e3d13d4/images/encryption/encryption.go#L264), the cycle will exit with a nil error, thus, the authorization check passes incorrectly. 
Let's take for example the case where the cycle checks the first manifest in the collection (e.g. for amd64) on an arm/arm64 machine, the children of this manifest are not found since this is not the target platform and they are not pulled -> the authorization check passes incorrectly. This issue is rarely reproducible on an amd64 machine as usually, this is the first manifest in the index descriptor.

**Comment by stefanberger** [comment]
Do you have examples of command lines that you used and ran into this issue?

**Comment by dimitar-dimitrow** [comment]
```
# ctr-enc -n issue i pull docker.io/library/bash:latest
# ctr-enc -n issue i encrypt --recipient jwe:/home/pi/develop/mypubkey.pem docker.io/library/bash:latest
# ctr-enc -n issue run -t --key /home/pi/develop/mykey.pem docker.io/library/bash:latest with_key
bash-5.1# exit
exit
# ctr-enc -n issue run -t docker.io/library/bash:latest without_key
bash-5.1# exit
exit
```

Result: The second container **without_key** runs without providing the private key.
Expected: Authorization check fails for **without_key**, the container does not run.

**Comment by stefanberger** [comment]
And you are trying this on something other than amd64?

**Comment by dimitar-dimitrow** [comment]
Yes, on raspberry(armv6l). This issue is rarely reproducible on an amd64 machine as usually, this is the first manifest in the index descriptor. In the case of docker.io/library/bash:latest the first manifest is indeed the amd64 one, so you won't be able to reproduce it on amd64 machine.

**Comment by stefanberger** [comment]
I now have a pending PR. @dimitar-dimitrow , maybe you can give it a try. 

https://github.com/stefanberger/imgcrypt/tree/fix_issue_69

**Comment by stefanberger** [comment]
@dimitar-dimitrow I am going to create v1.1.4 once a few more things are merged. I will create a CVE referencing your report. Thanks.
