### ISSUE TITLE
Error when import images from tar file with platforms linux/arm64 on jetson AGX jetpack 4.4.1

### ISSUE THREAD

**Issue by tranducanhbk** [containerd/imgcrypt#94]
I run the script below on Jetson AGX jetpack 4.4.1 (R32 (release), REVISION: 4.4, GCID: 23942405, BOARD: t186ref, EABI: aarch64, DATE: Fri Oct 16 19:37:08 UTC 2020)

```
#!/usr/bin/env bash

ALPINE=quay.io/jitesoft/alpine:latest
ALPINE_ENC=quay.io/jitesoft/alpine:enc
ALPINE_ENC_IMPORT_BASE=quay.io/jitesoft/alpine-import
PLATFORM="--all-platforms"

sudo ctr-enc images rm --sync ${ALPINE_ENC}

sudo ctr-enc images pull ${PLATFORM} ${ALPINE}
sudo ctr-enc images layerinfo ${ALPINE}

sudo ctr-enc images encrypt --platform linux/arm64 --recipient jwe:mypubkey.pem ${ALPINE} ${ALPINE_ENC}
sudo ctr-enc images layerinfo ${ALPINE_ENC}
rm -f image.tar

sudo ctr-enc images export ${PLATFORM} image.tar ${ALPINE_ENC}
sudo ctr-enc images rm --sync ${ALPINE_ENC} ${ALPINE}

sudo ctr-enc images import ${PLATFORM} --base-name ${ALPINE_ENC_IMPORT_BASE} --skip-decrypt-auth --key mykey.pem image.tar
```

Then error happends
![image](https://user-images.githubusercontent.com/54969565/191564458-da44451e-d739-47e8-8235-c303bef08ec0.png)

When i use platforms amd64, ppc64le everthings is fine.

**Comment by stefanberger** [comment]
After all the previous discussions (https://github.com/containerd/imgcrypt/issues/89) and me not being able to recreate the issue on amd64 and ppc64 ... : what version of golang are you running? Can you install the latest version and recompile everything with go-1.19.1?

**Comment by tranducanhbk** [comment]
I alread install go-1.19-1 but no change
![image](https://user-images.githubusercontent.com/54969565/191691316-ffee2e8e-44e8-40bf-86e0-920dfe8a5df8.png)

**Comment by tranducanhbk** [comment]
Now i can import successfully after sudo make uninstall and install.
Maybe when i clone new code need to uninstall before install

**Comment by stefanberger** [comment]
> Now i can import successfully after sudo make uninstall and install.

@tranducanhbk Are you saying that it works now?

**Comment by tranducanhbk** [comment]
yes. it work now

**Comment by stefanberger** [comment]
Then we can close the issue?

**Comment by stefanberger** [comment]
Since it works now we can close the issue. No point in keeping it open.
