### ISSUE TITLE
Missing support for `zstd` compressed images

### ISSUE THREAD

**Issue by k-gostev** [containerd/imgcrypt#95]
## Issue Description:
It seems that working with an image that have a layer with media type `application/vnd.oci.image.layer.v1.tar+zstd`  is not possible. When I try to encrypt or even use `layerinfo` I see that the following error is returned:

```log
ctr: unhandled media type application/vnd.oci.image.layer.v1.tar+zstd: invalid argument
```

Also `$ ctr-enc containers create repo:port/zstd-image:latest some-id` fails with:

```log
ctr: you are not authorized to use this image: bad/unhandled MediaType application/vnd.oci.image.layer.v1.tar+zstd in encryptChildren
```

The `zstd` compression format is supported by `containerd` and for example `$ ctr containers create repo:port/zstd-image:latest hello-world-zstd` is working as expected and the desired container is created successfully.

## Steps to reproduce:
To reproduce the issue one can use [skopeo](https://github.com/containers/skopeo) to change the compression of a simple hello-world image and then push it to a private/[local registry](https://docs.docker.com/registry/), e.g.:

1. Use [skopeo copy](https://github.com/containers/skopeo/blob/main/docs/skopeo-copy.1.md) to create a zstd-compressed image and push it locally:
```sh
$ skopeo copy --dest-compress-format=zstd docker://hello-world docker://<some-plain-http-local-ip:port>/hello-world-zstd:latest --dest-tls-verify=false
```

2. Use [skopeo inspect](https://github.com/containers/skopeo/blob/main/docs/skopeo-inspect.1.md) to check the result pushed image compression:

```sh
$ skopeo inspect --raw docker://<some-plain-http-local-ip:port>/hello-world-zstd:latest --tls-verify=false | jq -r '.layers[].mediaType'
```

3. Pull the image:

```sh
$ ctr-enc image pull --plain-http <some-plain-http-local-ip:port>/hello-world-zstd:latest
```

4. Try any of the following commands:

```sh
$ ctr-enc image encrypt <some-plain-http-local-ip:port>/hello-world-zstd:latest --recipient=pgp:foo@bar.com
```

```sh
$ ctr-enc containers create <some-plain-http-local-ip:port>/zstd-image:latest some-id
```

## Proposal:
In my opinion the compression part of the media type should not be taken into account as (please correct me if I am wrong) it is not relevant to the encryption process. So, the checks that are done [here](https://github.com/containerd/imgcrypt/blob/2c93cef1eb0b48263d16f5f2289a1a3f49a17d39/images/encryption/encryption.go#L109-L127), [here](https://github.com/containerd/imgcrypt/blob/2c93cef1eb0b48263d16f5f2289a1a3f49a17d39/images/encryption/encryption.go#L283-L315) and probably in some other parts of the code that I haven't explore, could be refactored in a way that disregards the compression type, whether it is `zstd` or something else.
 As a proof of my thoughts I have done locally the most simple test, which is just adding `application/vnd.oci.image.layer.v1.tar+zstd` and `application/vnd.oci.image.layer.v1.tar+zstd+encrypted` to the `switch/case` blocks in the functions linked above and as expected the encryption and creation of the container was successful. So, I think that it would be nice to have more flexibility regarding the verification of media types that are supported by the library.

**Comment by stefanberger** [comment]
Thanks for reporting this. Do you have a patch I can just apply with the zstd changes or can you send PR ?

**Comment by stefanberger** [comment]
I sent this PR now to ocircyrpt: https://github.com/containers/ocicrypt/pull/68

**Comment by k-gostev** [comment]
Thanks @stefanberger! I will prepare a PR for this issue.

**Comment by stefanberger** [comment]
Add a PR now that should resolve the issue.
